### ISSUE TITLE
XDebug scripts are hardcoded to a specific php version.

### ISSUE THREAD

**Issue by vincent-w2w** [johanvanhelden/dockerhero#38]
This line is hardcoded to a specific php version on the workspace and should probably reference `php -v` to determine for what version the extension should enable.

https://github.com/johanvanhelden/dockerhero/blob/4d221d7303b6a1c2170940ea3f6c0e19797b11b2/scripts/xdebug/start.sh#L11

**Comment by johanvanhelden** [comment]
This has been fixed in 1.7.1 with the following commit: https://github.com/johanvanhelden/dockerhero/commit/fb2584cf3de72016e33c8136766e4f74afc57a40
