### ISSUE TITLE
Connecting to services running on host computer

### ISSUE THREAD

**Issue by sanderg93** [johanvanhelden/dockerhero#47]
Can I connect to the host computer running an API for example? http://localhost:8000 does not seem to work atm.

**Comment by johanvanhelden** [comment]
Hmm, I have never had to use this before so I would have to look into that to see how you do this with Docker.

Could you tell me your use case, so I can try it myself? Is there some tool you want to access from within Docker?

You can also try this answer from StackOverflow, depending on your OS: 
https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container/43541732#43541732

**Comment by sanderg93** [comment]
I was running an azure functions app with azure functions cli 3.*. This binds the process to localhost:7071 automatically. Your pointer worked for me in connecting to localhost but the azure functions cli still blocked it for some reason. Now I just connect via my local IP address and then it works! Thanks for your help

**Comment by johanvanhelden** [comment]
Happy to hear you got it working! Thanks for letting me know.
