### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO) on docker-compose up

### ISSUE THREAD

**Issue by RoySijnesael** [johanvanhelden/dockerhero#58]
Hi, I'm getting this error after running `docker-compose up`;

> docker-compose up
Starting dockerhero_db        ... done
Starting dockerhero_workspace ... done
Starting dockerhero_redis     ... done
Starting dockerhero_mail      ... done
Starting dockerhero_php       ... done
Starting dockerhero_web       ... done
Attaching to dockerhero_workspace, dockerhero_redis, dockerhero_db, dockerhero_mail, dockerhero_php, dockerhero_web
db_1         | 2021-09-07 12:23:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
php_1        | /var/crons/crons: No such file or directory
mail_1       | [HTTP] Binding to address: 0.0.0.0:8025
mail_1       | Creating API v1 with WebPath:
mail_1       | Creating API v2 with WebPath:
mail_1       | 2021/09/07 12:23:12 Using in-memory storage
mail_1       | 2021/09/07 12:23:12 [SMTP] Binding to address: 0.0.0.0:1025
mail_1       | 2021/09/07 12:23:12 Serving under http://0.0.0.0:8025/
db_1         | 2021-09-07 12:23:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
php_1        | [07-Sep-2021 12:23:12] NOTICE: fpm is running, pid 10
db_1         | 2021-09-07 12:23:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
php_1        | [07-Sep-2021 12:23:12] NOTICE: ready to handle connections
redis_1      | 1:C 07 Sep 2021 12:23:11.948 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1      | 1:C 07 Sep 2021 12:23:11.948 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1      | 1:C 07 Sep 2021 12:23:11.948 # Configuration loaded
db_1         | 2021-09-07T12:23:12.352148Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1         | 2021-09-07T12:23:12.352207Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
db_1         | 2021-09-07T12:23:12.353413Z 0 [Note] mysqld (mysqld 5.7.34) starting as process 1 ...
db_1         | 2021-09-07T12:23:12.356458Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1         | 2021-09-07T12:23:12.356504Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2021-09-07T12:23:12.356509Z 0 [Note] InnoDB: Uses event mutexes
db_1         | 2021-09-07T12:23:12.356511Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1         | 2021-09-07T12:23:12.356514Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1         | 2021-09-07T12:23:12.356516Z 0 [Note] InnoDB: Using Linux native AIO
redis_1      | 1:M 07 Sep 2021 12:23:11.949 * monotonic clock: POSIX clock_gettime
web_1        | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web_1        | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
db_1         | 2021-09-07T12:23:12.356717Z 0 [Note] InnoDB: Number of pools: 1
db_1         | 2021-09-07T12:23:12.356806Z 0 [Note] InnoDB: Using CPU crc32 instructions
workspace_1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
workspace_1  | *** Running /etc/my_init.d/10_syslog-ng.init...
workspace_1  | [2021-09-07T12:23:11.795221] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.25 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.13'
workspace_1  | [2021-09-07T12:23:11.811148] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
workspace_1  | Sep  7 12:23:11 4a49bf16be1e syslog-ng[13]: syslog-ng starting up; version='3.25.1'
workspace_1  | Sep  7 12:23:11 4a49bf16be1e syslog-ng[13]: WARNING: log-fifo-size() works differently starting with syslog-ng 3.22 to avoid dropping flow-controlled messages when log-fifo-size() is misconfigured. From now on, log-fifo-size() only affects messages that are not flow-controlled. (Flow-controlled log paths have the flags(flow-control) option set.) To enable the new behaviour, update the @version string in your configuration and consider lowering the value of log-fifo-size().;
workspace_1  | *** Booting runit daemon...
workspace_1  | *** Runit started as PID 21
workspace_1  | Sep  7 12:23:12 4a49bf16be1e cron[24]: (CRON) INFO (pidfile fd = 3)
workspace_1  | Sep  7 12:23:12 4a49bf16be1e cron[24]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
db_1         | 2021-09-07T12:23:12.358161Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
redis_1      | 1:M 07 Sep 2021 12:23:11.950 * Running mode=standalone, port=6379.
redis_1      | 1:M 07 Sep 2021 12:23:11.950 # Server initialized
web_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db_1         | 2021-09-07T12:23:12.367717Z 0 [Note] InnoDB: Completed initialization of buffer pool
web_1        | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
redis_1      | 1:M 07 Sep 2021 12:23:11.950 * Ready to accept connections
db_1         | 2021-09-07T12:23:12.369635Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2021-09-07T12:23:12.381406Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
web_1        | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
db_1         | 2021-09-07T12:23:12.382578Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12664735
db_1         | 2021-09-07T12:23:12.382621Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12664744
db_1         | 2021-09-07T12:23:12.382626Z 0 [Note] InnoDB: Database was not shutdown normally!
db_1         | 2021-09-07T12:23:12.382629Z 0 [Note] InnoDB: Starting crash recovery.
web_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
db_1         | 2021-09-07T12:23:12.494151Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1         | 2021-09-07T12:23:12.494204Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2021-09-07T12:23:12.494273Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2021-09-07T12:23:12.528603Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2021-09-07T12:23:12.529178Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1         | 2021-09-07T12:23:12.529246Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1         | 2021-09-07T12:23:12.529875Z 0 [Note] InnoDB: Waiting for purge to start
db_1         | 2021-09-07T12:23:12.580157Z 0 [Note] InnoDB: 5.7.34 started; log sequence number 12664744
db_1         | 2021-09-07T12:23:12.580429Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2021-09-07T12:23:12.580625Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1         | 2021-09-07T12:23:12.582555Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210907 12:23:12
db_1         | 2021-09-07T12:23:12.585639Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1         | 2021-09-07T12:23:12.585675Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1         | 2021-09-07T12:23:12.586227Z 0 [Warning] CA certificate ca.pem is self signed.
db_1         | 2021-09-07T12:23:12.586318Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
web_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
db_1         | 2021-09-07T12:23:12.586781Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1         | 2021-09-07T12:23:12.586843Z 0 [Note] IPv6 is available.
db_1         | 2021-09-07T12:23:12.586861Z 0 [Note]   - '::' resolves to '::';
db_1         | 2021-09-07T12:23:12.586879Z 0 [Note] Server socket created on IP: '::'.
db_1         | 2021-09-07T12:23:12.590226Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1         | 2021-09-07T12:23:12.597801Z 0 [Note] Event Scheduler: Loaded 0 events
db_1         | 2021-09-07T12:23:12.598025Z 0 [Note] mysqld: ready for connections.
db_1         | Version: '5.7.34'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
web_1        | /docker-entrypoint.sh: Configuration complete; ready for start up
web_1        | 2021/09/07 12:23:13 [notice] 1#1: using the "epoll" event method
web_1        | 2021/09/07 12:23:13 [notice] 1#1: nginx/1.20.1
web_1        | 2021/09/07 12:23:13 [notice] 1#1: built by gcc 8.3.0 (Debian 8.3.0-6)
web_1        | 2021/09/07 12:23:13 [notice] 1#1: OS: Linux 5.10.25-linuxkit
web_1        | 2021/09/07 12:23:13 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
web_1        | 2021/09/07 12:23:13 [notice] 1#1: start worker processes
web_1        | 2021/09/07 12:23:13 [notice] 1#1: start worker process 31
web_1        | 2021/09/07 12:23:13 [notice] 1#1: start worker process 32
web_1        | 2021/09/07 12:23:13 [notice] 1#1: start worker process 33
web_1        | 2021/09/07 12:23:13 [notice] 1#1: start worker process 34
db_1         | 2021-09-07T12:23:42.041849Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)

I'm trying to migrate some tables for a Laravel application, but it can't connect to the database;
`Access denied for user 'projectname'@'172.25.0.10'`

I have no clue if I'm looking over something, please let me know!

**Comment by johanvanhelden** [comment]
What do you get when you visit phpmyadmin.localtest.me ?

**Comment by RoySijnesael** [comment]
It shows the phpmyadmin page (with a dockerhero db, and the default dbs)

**Comment by johanvanhelden** [comment]
Great, that means everything is working properly.

So I suggest you [create a new database](http://phpmyadmin.localtest.me/index.php?route=/server/databases) for your application using the name you see in the `DB_DATABASE` section of your .env file.

And then you can either [create a new user](http://phpmyadmin.localtest.me/index.php?route=/server/privileges&adduser=1) for that database and grant it privileges or use the root user like so:
```
DB_DATABASE=my_application_db
DB_USERNAME=root
DB_PASSWORD=dockerhero
```

There is no issue with Dockerhero here as far as I can see.

**Comment by RoySijnesael** [comment]
Awesome, looks like that's working. Thanks so much!
