### ISSUE TITLE
Run Vue CLI inside project/folder

### ISSUE THREAD

**Issue by makrosloro** [johanvanhelden/dockerhero#76]
Is there a way to launch npm run serve and access via "mydomain.localtest.me:8080" ?

**Comment by johanvanhelden** [comment]
I don't use Vue CLI myself anymore. But when I used it, I ran Vue CLI outside of docker.

**Comment by makrosloro** [comment]
Yes, it's a solution but I want to take advantage of *.localtest.me domains.

- app.localtest.me:8080
- api.localtest.me

**Comment by makrosloro** [comment]
@johanvanhelden I've sent an invitation to my private project repo based on Vue

**Comment by johanvanhelden** [comment]
> > Do you have a repository I can use to test this?
> 
> @johanvanhelden I've sent an invitation to my private project repo based on Vue. You can download it and try under a *.localtest.me domain

Sorry, the invitation has expired. I can not accept it anymore. Could you please send it again?
