### ISSUE TITLE
Configure XDebug with PHPStorm

### ISSUE THREAD

**Issue by makrosloro** [johanvanhelden/dockerhero#77]
Is it possible to config XDebug on PHPStorm. Every attempt was completely frustrating for me...

Here is a screenshot after start.sh xDebug
![imagen](https://user-images.githubusercontent.com/46315765/174828421-21766292-d162-425a-9a18-a5239a40c509.png)

Here another Screenshot where xDebug seems not installed...
![imagen](https://user-images.githubusercontent.com/46315765/174828544-e70055ff-9d4f-4393-9853-b2aa5184807f.png)

**Comment by johanvanhelden** [comment]
I'm sorry, I do not use PHPStorm and can not activate a trail license. Maybe someone who uses PHPStorm can help you out.

**Comment by Strongleong** [comment]
I used PHPStorm with Dockerhero and I had successfully set up XDebug. But sadly I am no longer use PHPStorm and I don't remember exactly what I had to do, but I remember that I spend a lot of time tinkering with path mappings before I got it to work
